version: '3.8'

services:

  mysql-server-db:
    image: mysql
    container_name: mysql-server-db_api
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'Temporal01*'
      MYSQL_DATABASE: 'GLWINBA_API'
    ports:
      - '3306:3306'
    volumes:
      - mysqlvolume:/var/lib/mysql

  nodejs:
    container_name: nodejs_api
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-server-db
    ports:
      - 8080:8080
    volumes:
      - /usr/src/app/node_modules
    environment:
      DB_HOST: 'mysql-server-db'
      DB_PORT: '3306'
      DB_USER: 'root'
      DB_PASSWORD: 'Temporal01*'
      DB_NAME: 'GLWINBA_API'
    links:
      - mysql-server-db

volumes: 
  sqlvolume:
    driver: local
  mysqlvolume:
    driver: local